# Install script for directory: /home/nitish/nikku/GCompris-qt/src/activities

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/gcompris-qt/rcc" TYPE FILE FILES "/home/nitish/nikku/GCompris-qt-build/share/gcompris-qt/rcc/activities.rcc")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/menu/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/advanced_colors/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/algebra_by/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/algebra_div/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/algebra_minus/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/algebra_plus/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/algorithm/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/align4/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/align4-2players/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/alphabet-sequence/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/babymatch/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/babyshapes/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/baby_wordprocessor/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/balancebox/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/ballcatch/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/braille_alphabets/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/braille_fun/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/canal_lock/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/chess/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/chess_2players/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/chess_partyend/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/chronos/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/clickanddraw/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/clickgame/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/click_on_letter/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/click_on_letter_up/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/clockgame/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/color_mix/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/color_mix_light/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/colors/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/details/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/drawletters/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/drawnumber/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/enumerate/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/erase/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/erase_2clic/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/erase_clic/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/explore_farm_animals/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/explore_monuments/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/explore_world_animals/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/explore_world_music/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/fifteen/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/followline/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/football/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/geo-country/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/geography/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/gletters/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/gnumch-equality/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/gnumch-factors/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/gnumch-inequality/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/gnumch-multiples/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/gnumch-primes/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/graph-coloring/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/guessnumber/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/hangman/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/hanoi/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/hanoi_real/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/hexagon/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/imagename/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/instruments/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/intro_gravity/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/land_safe/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/lang/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/leftright/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/letter-in-word/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/lightsoff/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/louis-braille/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/magic-hat-minus/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/magic-hat-plus/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/maze/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/mazeinvisible/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/mazerelative/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/melody/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-enumerate/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-math-add/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-math-add-minus/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-math-add-minus-mult-div/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-math-add-minus-mult-div-tux/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-math-add-minus-tux/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-math-add-tux/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-math-div/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-math-div-tux/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-math-minus/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-math-minus-tux/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-math-mult/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-math-mult-div/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-math-mult-div-tux/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-math-mult-tux/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-sound/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-sound-tux/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-tux/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/memory-wordnumber/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/mining/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/missing-letter/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/money/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/money_back/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/money_back_cents/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/money_cents/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/mosaic/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/NitishDemo/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/numbers-odd-even/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/paintings/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/penalty/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/photo_hunter/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/planegame/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/readingh/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/readingv/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/redraw/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/redraw_symmetrical/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/renewable_energy/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/reversecount/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/roman_numerals/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/scalesboard/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/scalesboard_weight/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/scalesboard_weight_avoirdupois/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/simplepaint/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/smallnumbers/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/smallnumbers2/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/sudoku/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/superbrain/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/tangram/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/target/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/tic_tac_toe/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/tic_tac_toe_2players/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/traffic/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/watercycle/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/wordsgame/cmake_install.cmake")
  INCLUDE("/home/nitish/nikku/GCompris-qt-build/src/activities/zindagi/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

